# Generated by Django 4.2.4 on 2023-08-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_head_paragraph', models.TextField()),
                ('contact_head', models.CharField(max_length=255)),
                ('contact_paragraph', models.CharField(max_length=255)),
                ('contact_map_info', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=255)),
            ],
        ),
    ]
