# Generated by Django 4.2.4 on 2023-08-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_contact_contactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='contact_map',
            field=models.TextField(default='notfound'),
        ),
    ]
