# Generated by Django 4.2.4 on 2023-08-19 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star1', models.BooleanField(default=False)),
                ('star2', models.BooleanField(default=False)),
                ('star3', models.BooleanField(default=False)),
                ('star4', models.BooleanField(default=False)),
                ('star5', models.BooleanField(default=False)),
            ],
        ),
    ]
