# Generated by Django 4.2.4 on 2023-08-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_review_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='product_name',
            field=models.ImageField(upload_to=''),
        ),
    ]
