# Generated by Django 4.2.4 on 2023-08-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_category', models.CharField(max_length=255)),
                ('home_head', models.CharField(max_length=255)),
                ('home_button', models.CharField(max_length=255)),
                ('home_collection', models.CharField(max_length=255)),
                ('home_collection_head', models.CharField(max_length=255)),
            ],
        ),
    ]
