# Generated by Django 4.2.4 on 2023-08-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_homedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('head', models.CharField(max_length=255)),
                ('btn', models.CharField(max_length=255)),
                ('collection1', models.CharField(max_length=255)),
                ('collection_head1', models.CharField(max_length=255)),
                ('men_title', models.CharField(max_length=255)),
                ('men_head', models.CharField(max_length=255)),
                ('men_btn', models.CharField(max_length=255)),
                ('middle_title', models.CharField(max_length=255)),
                ('middle_head', models.CharField(max_length=255)),
                ('middle_btn', models.CharField(max_length=255)),
                ('women_title', models.CharField(max_length=255)),
                ('women_head', models.CharField(max_length=255)),
                ('women_paragraph', models.TextField()),
                ('womne_btn', models.CharField(max_length=255)),
                ('collection2', models.CharField(max_length=255)),
                ('collection_head2', models.CharField(max_length=255)),
                ('review_paragraph', models.TextField()),
            ],
        ),
    ]
