# Generated by Django 4.2.4 on 2023-08-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_intro_first_paragraph', models.TextField()),
                ('about_intro_second_paragraph', models.TextField()),
                ('about_image_left_text_head', models.TextField()),
                ('about_image_left_text_paragraph', models.TextField()),
                ('about_image_right_first_paragraph', models.TextField()),
                ('about_image_right_second_paragraph', models.TextField()),
                ('about_middle_head', models.TextField()),
                ('about_middle_paragraph', models.TextField()),
                ('about_last_section_head', models.TextField()),
                ('about_last_section_first_paragraph', models.TextField()),
                ('about_last_section_second_paragraph', models.TextField()),
            ],
        ),
    ]
