# Generated by Django 4.2.4 on 2023-08-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutus_about_image_left_text_head_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about_image_left_text_head',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_image_left_text_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_image_right_first_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_image_right_second_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_intro_first_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_intro_second_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_last_section_first_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_last_section_head',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_last_section_second_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_middle_head',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='about_middle_paragraph',
            field=models.TextField(),
        ),
    ]
